// Generated by gencpp from file geo2tf/geometry.msg
// DO NOT EDIT!


#ifndef GEO2TF_MESSAGE_GEOMETRY_H
#define GEO2TF_MESSAGE_GEOMETRY_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace geo2tf
{
template <class ContainerAllocator>
struct geometry_
{
  typedef geometry_<ContainerAllocator> Type;

  geometry_()
    : x(0.0)
    , y(0.0)
    , z(0.0)
    , quaternion_x(0.0)
    , quaternion_y(0.0)
    , quaternion_z(0.0)
    , quaternion_w(0.0)  {
    }
  geometry_(const ContainerAllocator& _alloc)
    : x(0.0)
    , y(0.0)
    , z(0.0)
    , quaternion_x(0.0)
    , quaternion_y(0.0)
    , quaternion_z(0.0)
    , quaternion_w(0.0)  {
  (void)_alloc;
    }



   typedef double _x_type;
  _x_type x;

   typedef double _y_type;
  _y_type y;

   typedef double _z_type;
  _z_type z;

   typedef double _quaternion_x_type;
  _quaternion_x_type quaternion_x;

   typedef double _quaternion_y_type;
  _quaternion_y_type quaternion_y;

   typedef double _quaternion_z_type;
  _quaternion_z_type quaternion_z;

   typedef double _quaternion_w_type;
  _quaternion_w_type quaternion_w;





  typedef boost::shared_ptr< ::geo2tf::geometry_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::geo2tf::geometry_<ContainerAllocator> const> ConstPtr;

}; // struct geometry_

typedef ::geo2tf::geometry_<std::allocator<void> > geometry;

typedef boost::shared_ptr< ::geo2tf::geometry > geometryPtr;
typedef boost::shared_ptr< ::geo2tf::geometry const> geometryConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::geo2tf::geometry_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::geo2tf::geometry_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace geo2tf

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'geo2tf': ['/home/boyuan/VCLA/practice_ws/src/geo2tf/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::geo2tf::geometry_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::geo2tf::geometry_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::geo2tf::geometry_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::geo2tf::geometry_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::geo2tf::geometry_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::geo2tf::geometry_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::geo2tf::geometry_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dce9e430f28a40b69510d1179e073686";
  }

  static const char* value(const ::geo2tf::geometry_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xdce9e430f28a40b6ULL;
  static const uint64_t static_value2 = 0x9510d1179e073686ULL;
};

template<class ContainerAllocator>
struct DataType< ::geo2tf::geometry_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geo2tf/geometry";
  }

  static const char* value(const ::geo2tf::geometry_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::geo2tf::geometry_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 x\n\
float64 y\n\
float64 z\n\
float64 quaternion_x\n\
float64 quaternion_y\n\
float64 quaternion_z\n\
float64 quaternion_w\n\
";
  }

  static const char* value(const ::geo2tf::geometry_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::geo2tf::geometry_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.z);
      stream.next(m.quaternion_x);
      stream.next(m.quaternion_y);
      stream.next(m.quaternion_z);
      stream.next(m.quaternion_w);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct geometry_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::geo2tf::geometry_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::geo2tf::geometry_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<double>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<double>::stream(s, indent + "  ", v.y);
    s << indent << "z: ";
    Printer<double>::stream(s, indent + "  ", v.z);
    s << indent << "quaternion_x: ";
    Printer<double>::stream(s, indent + "  ", v.quaternion_x);
    s << indent << "quaternion_y: ";
    Printer<double>::stream(s, indent + "  ", v.quaternion_y);
    s << indent << "quaternion_z: ";
    Printer<double>::stream(s, indent + "  ", v.quaternion_z);
    s << indent << "quaternion_w: ";
    Printer<double>::stream(s, indent + "  ", v.quaternion_w);
  }
};

} // namespace message_operations
} // namespace ros

#endif // GEO2TF_MESSAGE_GEOMETRY_H
