// Generated by gencpp from file eight_queen/queens.msg
// DO NOT EDIT!


#ifndef EIGHT_QUEEN_MESSAGE_QUEENS_H
#define EIGHT_QUEEN_MESSAGE_QUEENS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace eight_queen
{
template <class ContainerAllocator>
struct queens_
{
  typedef queens_<ContainerAllocator> Type;

  queens_()
    : result()  {
      result.assign(0);
  }
  queens_(const ContainerAllocator& _alloc)
    : result()  {
  (void)_alloc;
      result.assign(0);
  }



   typedef boost::array<int32_t, 8>  _result_type;
  _result_type result;





  typedef boost::shared_ptr< ::eight_queen::queens_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::eight_queen::queens_<ContainerAllocator> const> ConstPtr;

}; // struct queens_

typedef ::eight_queen::queens_<std::allocator<void> > queens;

typedef boost::shared_ptr< ::eight_queen::queens > queensPtr;
typedef boost::shared_ptr< ::eight_queen::queens const> queensConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::eight_queen::queens_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::eight_queen::queens_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace eight_queen

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'eight_queen': ['/home/boyuan/VCLA/practice_ws/src/eight_queen/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::eight_queen::queens_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::eight_queen::queens_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::eight_queen::queens_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::eight_queen::queens_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::eight_queen::queens_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::eight_queen::queens_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::eight_queen::queens_<ContainerAllocator> >
{
  static const char* value()
  {
    return "12c75e77d788a697d2f52c983b334323";
  }

  static const char* value(const ::eight_queen::queens_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x12c75e77d788a697ULL;
  static const uint64_t static_value2 = 0xd2f52c983b334323ULL;
};

template<class ContainerAllocator>
struct DataType< ::eight_queen::queens_<ContainerAllocator> >
{
  static const char* value()
  {
    return "eight_queen/queens";
  }

  static const char* value(const ::eight_queen::queens_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::eight_queen::queens_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32[8] result\n\
";
  }

  static const char* value(const ::eight_queen::queens_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::eight_queen::queens_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.result);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct queens_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::eight_queen::queens_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::eight_queen::queens_<ContainerAllocator>& v)
  {
    s << indent << "result[]" << std::endl;
    for (size_t i = 0; i < v.result.size(); ++i)
    {
      s << indent << "  result[" << i << "]: ";
      Printer<int32_t>::stream(s, indent + "  ", v.result[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // EIGHT_QUEEN_MESSAGE_QUEENS_H
